config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'plans#index'
  resources :plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base

  self.data = [
    { id:1, name: "--"},
    { id:2, name: "習慣化"},
    { id:3, name: "勉強"},
    { id:4, name: "睡眠"},
    { id:5, name: "早起き"},
    { id:6, name: "ダイエット"},
    { id:7, name: "筋トレ"},
    { id:8, name: "食事"},
    { id:9, name: "ランニング"},
    { id:10, name: "マインドフルネス"},
    { id:11, name: "初心者"},
    { id:12, name: "その他"},
  ]
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :term
  belongs_to_active_hash :price
  has_many :plan_users
  has_many :users, through: :plan_users
  accepts_nested_attributes_for :plan_users, allow_destroy: true

  with_options presence: true do
    validates :image, unless: :was_attached?
    validates :name  
    validates :description
    validates :category_id
    validates :term_id
    validates :price_id
  end

  validates :category_id, :term_id, :price_id, numericality: { other_than: 1 ,message: 'を選択して下さい'} 
  has_one_attached :image
  def was_attached?
    self.image.attached?
  end
end

app/models/plan_user.rb
class PlanUser < ApplicationRecord
  belongs_to :user
  belongs_to :plan, optional: true

end

app/models/price.rb
class Price < ActiveHash::Base

  self.data = [
    { id:1, name: "--"},
    { id:2, name: "0"},
    { id:3, name: "1000"},
    { id:4, name: "3500"},
    { id:5, name: "5000"},
    { id:6, name: "10,000"},
    { id:7, name: "30,000"},
    { id:8, name: "50,000"},
    { id:9, name: "100,000"},
    { id:10, name: "200,000"},
  ]

end

app/models/term.rb
class Term < ActiveHash::Base

  self.data = [
    { id:1, name: "--"},
    { id:2, name: "10"},
    { id:3, name: "21"},
    { id:4, name: "60"},
    { id:5, name: "90"},
    { id:6, name: "180"},
]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :plan_users
         has_many :plans, through: :plan_users
         

         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: "は半角英数字で入力して下さい"
         
         validates :email, uniqueness: { case_sensitive: false }         
         validates :nickname, presence: true
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_parameter_sanitizers, if: :devise_controller?

  private

  def devise_parameter_sanitizers
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :move_to_index, except:  [:index, :show]
  before_action :set_plan,only: [:show]


  def index
    @plans =Plan.all.order("created_at DESC")
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      @plan.plan_users.create(user_id: current_user.id)
      redirect_to root_path
    else 
      render :new
    end
  end

  def show
  end

  private
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index     
    end
  end

  def plan_params
    params.require(:plan).permit(
      :image,
      :name,
      :description,
      :item,
      :category_id,
      :term_id,
      :price_id).
      merge(user_id: current_user.id)
  end

  # def plan_params
  #   params.require(:plan).permit(
  #     :image,
  #      :name,
  #       :description,
  #        :category_id,
  #         :term_id,
  #          :price_id,
  #            user_ids: []).merge(user_id: current_user.id)
  # end

  def set_plan
    @plan = Plan.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/86e10af58f.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/index.html.erb
<%= render "shared/header" %>
<div class="main">

  <%# プラン一覧 %>
      <% @plans.each do |plan| %>
        <%= link_to plan_path(plan.id), method: :get do %>
      <div class="content">
        <div class='plan-img-content'>
          <%= image_tag plan.image, class: "plan-img" %>
        </div>
        <div class='plan-info'>
          <h3 class='plan-name'>
            <%= plan.name %>
          </h3>
          <div class='plan-price'>
            <span><%= plan.price.name %>円</span>
            <div class='good-btn'>
              <%= image_tag "goodmark.png", class:"good-icon" %>
              <span class='good-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
  <%#/ プラン一覧 %>

</div>
<div class='planning-btn'>
  <span class='planning-btn-text'>計画を立てる</span>
  <%= link_to new_plan_path do %>
    <%= image_tag 'pen.png' , size: '185x50' ,class: "planning-btn-icon" %>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/plans/new.html.erb
<header class="new-plans-header">
  <%= link_to image_tag("dodo-logo.png", class:"dodo-icon-three"), "/" %>
<span class="header-text">プランの情報を入力</span>
</header>
<div class="plan-contents">

  <div class="plan-main">
    <%= form_with model: @plan, url: plans_path, method: :post ,local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
  
    <%#プラン画像%>
    <div class="img-upload">
      <div class="weight-bold-text">
        プラン画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%#/プラン画像%>

    <%#プラン説明%>
    <div class="new-plans">
      <div class="weight-bold-text">
        プラン名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"plans-text", id:"plan-name", placeholder:"プラン名（必須 40文字まで)", maxlength:"40" %>
      <div class="plans-explain">
        <div class="weight-bold-text">
          プランの概要
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"plans-text", id:"plan-info", placeholder:"プランの説明（どんなプランなのか簡単に記入してください）          例）このプランはプログラミング勉強をがんばるルームです！皆さん一緒にがんばりましょう！！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%#/プラン説明%>

    <%#プランで使うアイテム%>
      <div class="plans-item">
        <div class="weight-bold-text">
          アイテム
          <span class="any">任意</span>
        </div>
        <%=f.text_area :item, class:"plan-support", id:"plan-item", placeholder:"目標達成に向けて使うサービスや参考書を買いてください(特にない場合は空欄でも結構です)", maxlength:"1000" %>
      </div>
    <%#/プランで使うアイテム%>

    <%# 目標達成までの期間とカテゴリ,do価格について%>
    <div class="plans-detail">
      <div class="weight-bold-text">プランの詳細設定</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"plan-category"}) %>
        <div class="weight-bold-text">
          期間
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:term_id, Term.all, :id, :name, {}, {class:"select-box", id:"plan-term"}) %>
        <div class="weight-bold-text">
          do価格
          <span class="indispensable">必須</span>
        </div>
        <div class="question-text">
          <span>do価格について</span>
          <a class="question" href="#">?</a>
        </div>
        <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"select-box", id:"plan-price"}) %>

      </div>
    </div>
    <%#/目標達成までの期間とカテゴリ,do価格について %>

    <%# 下部ボタン %>
    <div class="decision-btn-contents">
      <%= f.submit "プランを決定する" ,class:"plan-btn" %>
     <br><%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
    <% end %>
</div>  

app/views/plans/show.html.erb
<%= render "shared/header" %>

<div class="plan-show">
  <div class="plan-box">
    <h2 class="name">
      <%= @plan.name %>
   </h2>

    <div class="plan-explain">プランの説明</div>
    <div class="plan-explain-box">
      <span><%= @plan.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <%# <tr>
          <th class="detail-plan">プランを計画した人</th>
        </tr> %>
        <tr>
          <th class="detail-plan">アイテム</th>
          <td class="detail-item detail-value"><%= @plan.item %></td>
        </tr>
        <tr>
          <th class="detail-plan">カテゴリー</th>
          <td class="detail-value"><%= @plan.category.name %></td>
        </tr>
        <tr>
          <th class="detail-plan">期間</th>
          <td class="detail-value"><%= @plan.term.name %></td>
        </tr>
      </tbody>
    </table>

    <div class="plan-price-box">
        <span class="detail-price"> 値段 </span>
      <span class="plan-detail-price">
        <%= @plan.price.name%>
      </span>
    </div>

    <div class="three-btn">
    <% if user_signed_in?%>
    <%if current_user.id == @plan.user_id %> 
    <%= link_to 'プランの編集', edit_plan_path(@plan.id), method: :get, class: "plan-edit-btn btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', plan_path(@plan.id), method: :delete, class:'plan-destroy btn' %>
    <% else  %>
    <%= link_to 'プランに参加する', "/",class:"plan-participate btn"%>
    <% end %>
    <% end %>
    </div>

      <div class="goodmark-btn">
        <%= image_tag "goodmark.png" ,class: "goodmark-icon" ,width:"20",height:"20"%>
        <span>いいね 0</span>
      </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='dodo-details'>
      <h2 class='footer-content-head'>dodoについて</h2>
      <ul>
        <li><%= link_to '製作者', "#", class: "footer-link" %></li>
        <li><%= link_to 'お問い合わせ', "#", class: "footer-link" %></li>
        <li><%= link_to 'dodo利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'dodoガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
        <li><%= link_to 'よくある質問', "#",class: "footer-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="header-inner">
    <div class="logo">
    <%= link_to image_tag("dodo-logo.png", class:"dodo-icon"), "/" %>
    </div>
    <nav class="header-nav">
      <div class="header-nav-item">
        <form class="form2">
          <input type="search" class="form2-input" placeholder="プランを検索" />
          <button type="submit" class="form2-button"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </nav>
  </div>
    <div class='lists-right'>
      <% if user_signed_in? %>
      <div class="header-user-item">
        <img src="https://placehold.jp/50x50.png" class="header-avatar" />
      <p><%= link_to current_user.nickname,'#', class: "user-nickname" %></p>
      </div>      
      <p><%= link_to 'ログアウト', destroy_user_session_path,method: :delete, class: "logout" %></p>
      <% else %>
      <p><%= link_to 'ログイン', new_user_session_path, class: "login" %></p>
      <p><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></p>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class="registration-header">
  <%= link_to image_tag("dodo-logo.png", class:"dodo-icon-second"), "/" %>
</header>